[package]
name = "strchunk"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
edition = "2018"

[features]
specialization = []

[dependencies]
bytes = "0.4"
range-split = { version = "0.1.0-beta.1", features = ["bytes"] }
